name: Create Github Tag & Release

on:
  workflow_dispatch:  # run manually

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          python-version: "3.11"

      - name: Install deps
        run: make install

      - name: Push commits and tags
        run: |
          TAG=$(uvx hatch version)
          git push origin HEAD
          git push origin ${{ env.TAG }}

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ env.TAG }}" --generate-notes
