name: Publish to PyPI on GitHub Release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Set up uv (3.11)
        uses: astral-sh/setup-uv@v3
        with:
          python-version: "3.11"

      - name: venv + deps
        run: |
          uv venv -p 3.11
          uv sync --dev

      - name: Build dists
        run: make clean build

      # OIDC publish to PyPI
      - name: Publish to PyPI (OIDC)
        uses: pypa/gh-action-pypi-publish@release/v1
