name: Tag on Merge to main

on:
  push:
    branches: [main]

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up uv (3.11)
        uses: astral-sh/setup-uv@v3
        with:
          python-version: "3.11"

      - name: venv + deps (minimal)
        run: |
          uv venv -p 3.11
          uv add --dev tomli-w || true
          uv sync --dev

      - name: Create tag from pyproject version (if missing)
        run: make tag
